hydra:
  run:
    dir: outputs/test/${model.modelname}/${model.ckpt.name}/${run_name}
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

# Global configurations shared between different modules
run_name: base

seed: 1234
logger_level: INFO

# Composing nested config with default
defaults:
  - _self_
  - data: cirr_blip2
  - test: all
  - machine: server
  - trainer: gpu
  - model: blip2
  #- model/ckpt: blip2_eva_clip_g
  - model/loss: hn_nce
  - trainer/logger: none

  - experiment: cirr_blip2

paths: ${machine.paths}
