modelname: blip2
_target_: src.model.blip2_cir.blip2_cir


model:
  _target_: src.model.blip2_cir.BLIP2Cir
  embed_dim: 256
  train_vit: False
  loss: ${model.loss}
  img_size: 224
  vit_model: "clip_L"
  max_txt_len: 35
  drop_path_rate: 0
  cross_attention_freq: 2
  use_grad_checkpoint: False
  vit_precision: "fp32"
  pooling: "mean"